name: Build Oneworx Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Project Dependencies
      run: yarn install

    - name: Create Missing log_creds.txt
      run: |
        echo "dummy-key" > log_creds.txt
        echo "dummy-secret" >> log_creds.txt
        echo "dummy-url" >> log_creds.txt
        echo "dummy-telemetry" >> log_creds.txt

    - name: Build Oneworx Windows Installer
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_ENV: production
      run: yarn build --win

    - name: Upload Windows Installer Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Oneworx-Windows-Installer
        path: dist_electron/bundled/
        retention-days: 30
